# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=1024)),
                ('desc', models.CharField(max_length=200)),
                ('clasif', models.CharField(choices=[('sd', 'Sin Definir'), ('ad', 'Adaptador'), ('di', 'Divergente'), ('co', 'Convergente'), ('as', 'Asimilador')], default='sd', max_length=2)),
                ('valid', models.BooleanField()),
            ],
        ),
    ]
