# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bentobox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='tags',
            field=models.CharField(default='prueba1,prueba2,prueba3,example', max_length=2048),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contenido',
            name='clasif',
            field=models.IntegerField(choices=[(0, 'No relevante'), (1, 'Relevante'), (2, 'Muy relevante')], default=1),
        ),
    ]
