# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bentobox', '0002_auto_20170612_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenido',
            old_name='clasif',
            new_name='clasif_ad',
        ),
        migrations.AddField(
            model_name='contenido',
            name='clasif_as',
            field=models.IntegerField(choices=[(0, 'No relevante'), (1, 'Relevante'), (2, 'Muy relevante')], default=1),
        ),
        migrations.AddField(
            model_name='contenido',
            name='clasif_co',
            field=models.IntegerField(choices=[(0, 'No relevante'), (1, 'Relevante'), (2, 'Muy relevante')], default=1),
        ),
        migrations.AddField(
            model_name='contenido',
            name='clasif_di',
            field=models.IntegerField(choices=[(0, 'No relevante'), (1, 'Relevante'), (2, 'Muy relevante')], default=1),
        ),
    ]
